packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - esbuild
  - sharp

ignoredBuiltDependencies:
  - "@firebase/util"
  - "@reown/appkit"
  - bufferutil
  - keccak
  - protobufjs
  - utf-8-validate

overrides:
  postcss: 8.5.10
  ws: 8.21.0
