import { LegalShell } from "../legal-shell";

export default function PrivacyPage() {
  return (
    <LegalShell eyebrow="DATA TRANSPARENCY" title="Privacy Notice" updated="August 11, 2026">
      <div className="legalNotice"><strong>Core principle:</strong> RMT never asks for or stores private keys or recovery phrases.</div>
      <div className="legalNotice"><strong>Paused systems:</strong> Profiles, referrals, phone-profile alerts, creator uploads and RMT Live are paused during terminal completion. Existing records and their access protections are preserved; the descriptions below explain data that earlier product versions may have collected.</div>
      <h2>Information visible onchain</h2>
      <p>Wallet addresses, token launches, trades, balances, approvals, reward claims, contract interactions, and transaction hashes are public blockchain data. That information may be permanent and can be analyzed by anyone.</p>
      <h2>Information handled by the interface</h2>
      <p>When you connect a wallet, the interface reads its public address, network, balances, positions, and claimable rewards. This information is used to render the requested experience and is not treated as a secret.</p>
      <h2>RMT account and secure sign-in</h2>
      <p>RMT offers one optional account through Privy. You may choose an email code, Google, a passkey, or an existing wallet. Google processes sign-in information only when you choose Google; Privy processes account, linked-account, device, network, and diagnostic information under its privacy terms. RMT verifies Privy’s signed identity on the server and exchanges it for a short-lived Firebase session used only for private RMT data.</p>
      <p>If you sign in, the display name, handle, desk note, terminal preferences, and watched token addresses you choose are synchronized to a Firebase workspace bound to that verified RMT account. RMT does not expose a second Firebase sign-in or trust an email supplied by the browser. Additional email, Google, passkey, and external-wallet methods can be linked to the account already open; starting separate unlinked sign-ins may create separate Privy identities. Selecting or changing a trading wallet does not change the profile owner, and account sign-in alone does not authorize a transaction.</p>
      <p>If you create an RMT invite, its permanent code and verified activation count are stored in the same private workspace. A referred account stores one private claim after that user signs in and saves a protected profile. RMT does not count invite-link clicks, expose referral relationships publicly, or enable referral rewards in this release.</p>
      <h2>Optional phone alerts</h2>
      <p>You may separately link and verify a phone number through Privy for future watchlist-alert delivery. Linking a phone does not enroll it in RMT texts. RMT collects current, express consent only when delivery is operational and you choose to enable it. Until then, the profile labels delivery as locked and sends nothing.</p>
      <p>When enabled, RMT stores a server-private keyed phone fingerprint, an authenticated encrypted copy of the delivery number, the consent version and time, the selected daily limit, and delivery or revocation state. The clear phone number is not stored in a browser-readable Firebase document. The messaging provider receives the number and alert text to deliver a triggered rule. RMT texts contain informational watchlist events only; they do not execute or authorize transactions. You can disable alerts in Profile or reply STOP. Message and data rates may apply.</p>
      <h2>Device-local information</h2>
      <p>Watchlists, watchlist alert rules, first-visit guide status, optional diagnostics preference and Position Guard state may remain in your browser so the terminal can work without a profile. Cloud profile synchronization and invite activation are paused. Existing cloud and local records are preserved and do not grant transaction authority. Clearing this site&apos;s browser data removes local copies. Wallet applications may separately retain connection permissions under their own privacy policies.</p>
      <h2>Optional anonymous experience measurements</h2>
      <p>RMT does not enable product diagnostics until a visitor chooses to help improve the interface. When enabled, the browser may submit a fixed set of broad milestones at most once per browser session, including opening a public trading surface, reaching Terminal, opening a discovered market, starting trade preparation, starting or completing wallet connection, reaching a protected quote, or requesting wallet review. The submitted record contains only the milestone, a coarse mobile or desktop category, and the measurement schema version.</p>
      <p>RMT does not include a wallet address, token address, token name, amount, search, profile, email, transaction, exact page, advertising identifier, cookie, or persistent visitor identifier in this record. The private administrator dashboard reviews the latest 14 days of daily aggregate counts. These counts are used to identify interface friction and are not used for advertising, wallet scoring, token ranking, or financial decisions. Hosting providers may still process ordinary request infrastructure data as described below. The setting can be changed at any time through Experience &amp; Privacy.</p>
      <h2>RMT Live and guest identities</h2>
      <p>RMT Live may create a persistent anonymous Firebase identity so a guest can participate without publishing a profile. Public messages show a pseudonymous guest label, not the Firebase identifier, email, wallet address, IP address, or device identifier. RMT privately retains the minimum identity mapping and moderation history needed to rate-limit abuse, enforce restrictions, and investigate reports. Public rooms are not private communications. Do not share recovery words, private keys, personal information, or confidential material.</p>
      <p>While the RMT Live panel is open, RMT may refresh a short-lived private presence record. The interface receives only an approximate aggregate count of recently active community identities. Presence records do not contain a public wallet, email, display name, or raw Firebase identifier, cannot be read by browser clients, expire from the active count automatically, and are not presented as site-wide analytics or an exact real-time roster.</p>
      <p>Signed-in members and pseudonymous guests may privately report a visible message using a structured safety reason. A report stores a limited snapshot of the reported public message, keyed pseudonymous reporter and author identifiers, its review status, and timestamps. Only the verified RMT administrator can access the report queue through the server. Moderation decisions may hide a message or temporarily restrict that community identity from posting and create a private audit record. These actions do not control a wallet, alter a profile, rank a token, or affect trading.</p>
      <p>RMT Live also accepts structured product feedback. The selected category, title, description, pseudonymous identity key, review state, and timestamps remain in a server-private feedback record. A separate public marker may show only the feedback identifier, broad category, timestamps, and submitted, under review, planned, shipped, or closed status. The submitting browser can save the random receipt identifier and use it to follow that public marker under Updates. It does not expose the description, reviewer note, wallet, email, profile, or reporter identity. Anyone who learns a receipt identifier can read the same limited marker, so it must not be treated as an authentication secret. The authenticated identity that created a submission can withdraw it: RMT deletes the private feedback record, closes the public marker, and retains a minimal private audit event without the feedback text or identity key. Feedback does not authorize transactions or automatically commit RMT to a feature.</p>
      <h2>Uploads and permanent metadata</h2>
      <p>Token artwork, creator-project logos, banners, galleries, update images, descriptions, and social links may be uploaded to IPFS through an external pinning provider. Creator media uploads require a verified profile assigned to that project. IPFS content may be public, copied, and difficult or impossible to remove. Do not upload personal, confidential, or unlawful information.</p>
      <h2>Infrastructure data</h2>
      <p>Hosting, database, authentication, RPC, wallet-connection, security, and content-delivery providers may process IP address, device, request, and diagnostic information to deliver and protect their services. To enforce shared community request limits, RMT derives a secret-keyed HMAC from the validated network address and operation type. Firestore stores that non-reversible bucket identifier with a bounded count and expiration time, not the raw network address. RMT does not sell personal information.</p>
      <h2>External market data and links</h2>
      <p>External market results are supplied by DEX Screener and link to third-party websites. Block explorers, wallets, DEXs, and social links have their own privacy practices. Review them before continuing.</p>
      <h2>Access and deletion requests</h2>
      <p>You can edit terminal preferences at any time. To reduce impersonation and rapid identity switching, changes to display name, handle, and desk note receive a 10-minute correction window and then a 24-hour protection period. An RMT Live feedback receipt offers self-service withdrawal while the original authenticated identity remains available in that browser or account. To request deletion of the associated cloud profile or other eligible private records, use the private project contact on the Support page from the same email account used to sign in. Public blockchain and IPFS records cannot be deleted by RMT.</p>
      <h2>Children and restricted users</h2>
      <p>RMT is not intended for anyone under 18. Do not use the service if local law prohibits access to blockchain trading or token-creation tools.</p>
      <h2>Questions</h2>
      <p>Use the Support page for the current privacy contact. Never send a private key, seed phrase, or recovery phrase in a support request.</p>
    </LegalShell>
  );
}
